
defaultDs:
  string:
    url: ${form.datasource.url}
    username: ${form.datasource.username}
    password: ${form.datasource.password}
    driverClassName: ${form.datasource.driver}
    connection-init-sqls: ${form.datasource.connection}
    validationQuery: ${form.datasource.vaildQuery}
    filters: stat
  int:
    initialSize: ${form.datasource.minSize}
    minIdle: ${form.datasource.minSize}
    maxActive: ${form.datasource.maxSize}
    maxPoolPreparedStatementPerConnectionSize: 20
  long:
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  boolean:
    testWhileIdle: true
    testOnBorrow: ${form.datasource.testOnBorrow}
    testOnReturn: false
    poolPreparedStatements: true

mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml


redxun:
  swagger:
    enabled: true
    title: 门户中心
    description: 门户文档
    version: 1.0
    base-package: com.redxun.form.core.controller
  cache-manager:
    configs:
      - key: form
        second: 300
      - key: portal_menu
        second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: form_tx_group
  enable-auto-data-source-proxy: true

  registry:
    type: nacos
    nacos:
      application: seata-server
      namespace: ${nacos.namespace:local}
      server-addr: ${nacos.address:localhost:8848}
      group: DEFAULT_GROUP
      userName:
      password:

  config:
    type: nacos
    nacos:
      namespace: ${nacos.namespace:local}
      serverAddr: ${nacos.address:localhost:8848}
      group: SEATA_GROUP
      cluster: default
      userName:
      password:
      data-id: seataServer.properties
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
# 注册开发者。
  cloud:
    nacos:
      discovery:
        metadata:
          developer: ray
logging:
  level:
    root: info
