
defaultDs:
  string:
    url: ${system.datasource.url}
    username: ${system.datasource.username}
    password: ${system.datasource.password}
    driverClassName: ${system.datasource.driver}
    connection-init-sqls: ${system.datasource.connection}
    validationQuery: ${system.datasource.vaildQuery}
    filters: stat
  int:
    initialSize: ${system.datasource.minSize}
    minIdle: ${system.datasource.minSize}
    maxActive: ${system.datasource.maxSize}
    maxPoolPreparedStatementPerConnectionSize: 20
  long:
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  boolean:
    testWhileIdle: true
    testOnBorrow: ${system.datasource.testOnBorrow}
    testOnReturn: false
    poolPreparedStatements: true

mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

redxun:
  swagger:
    enabled: true
    title: 系统管理中心
    description: 系统管理中心文档
    version: 1.0
    base-package: com.redxun.system.core.controller
  cache-manager:
    configs:
      - key: system
        second: 300
      - key: system_menu
        second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - sys_tree_cat
      - sys_tree
      - sys_dic
      - sys_app
      - sys_menu


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: system_tx_group
  enable-auto-data-source-proxy: false

  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos.address:localhost:8848}
      namespace: ${nacos.namespace:local}
      group: DEFAULT_GROUP
      userName:
      password:

  config:
    type: nacos
    nacos:
      serverAddr: ${nacos.address:localhost:8848}
      namespace: ${nacos.namespace:local}
      group: SEATA_GROUP
      cluster: default
      userName:
      password:
      data-id: seataServer.properties
spring:
  servlet:
    multipart:
      #maxFileSize 是单个文件大小
      #maxRequestSize是设置总上传的数据大小
      max-file-size: 50MB
      max-request-size: 50MB

  cloud:
    nacos:
      discovery:
        metadata:
          developer: ray
  messages:
    basename: i18n/system
    encoding: UTF-8

  devtools:
    restart:
      enabled: true

xxl-job:
  enabled: ${job.system:false}
  mode: nacos
  admin:
    admin-addresses: ${job.center:localhost:7878}
  executor:
    app-name: system-job #默认为 xxl-job-executor
    address: ${spring.application.name}
    #access-token: #默认为空
    log-path: logs/jpaas-job #默认为 logs/applogs/xxl-job/jobhandler
    log-retention-days: 10 #默认为 10
    #ip: #默认为空
    #port: 7679 #默认为 9999
