

defaultDs:
  string:
    url: ${user.datasource.url}
    username: ${user.datasource.username}
    password: ${user.datasource.password}
    driverClassName: ${user.datasource.driver}
    connection-init-sqls: ${user.datasource.connection}
    validationQuery: ${user.datasource.vaildQuery}
    filters: stat
  int:
    initialSize: ${user.datasource.minSize}
    minIdle: ${user.datasource.minSize}
    maxActive: ${user.datasource.maxSize}
    maxPoolPreparedStatementPerConnectionSize: 20
  long:
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  boolean:
    testWhileIdle: true
    testOnBorrow: ${user.datasource.testOnBorrow}
    testOnReturn: false
    poolPreparedStatements: true


mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

xxl-job:
  enabled: ${job.user:false}
  mode: nacos
  admin:
    admin-addresses: ${job.center:localhost:7878}
  executor:
    app-name: user-job #默认为 xxl-job-executor
    address: ${spring.application.name}
    #access-token: #默认为空
    log-path: logs/jpaas-job #默认为 logs/applogs/xxl-job/jobhandler
    log-retention-days: 10 #默认为 10
    #ip: #默认为空
    #port: 7678 #默认为 9999

redxun:
  #审计日志
  #audit-log:
  #  enabled: true
  #  log-type: db
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    jdbc-url: jdbc:mysql://${redxun.datasource.ip}:3306/jpaas-system?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  #    username: ${redxun.datasource.username}
  #    password: ${redxun.datasource.password}
  #聚合文档
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.redxun.user.org.controller
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: false
    ignoreTables:
      - os_user
      - sys_role_user
      - sys_role_menu
      - os_user_type
      - os_group_menu
      - os_inst_type_menu
      - os_inst_type_api
      - os_group_api


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: user_tx_group
  enable-auto-data-source-proxy: false

  registry:
    type: nacos
    nacos:
      application: seata-server
      namespace: ${nacos.namespace:local}
      server-addr: ${nacos.address:localhost:8848}
      group : DEFAULT_GROUP
      userName:
      password:

  config:
    type: nacos
    nacos:
      serverAddr: ${nacos.address:localhost:8848}
      namespace: ${nacos.namespace:local}
      group: SEATA_GROUP
      cluster: default
      userName:
      password:
      data-id: seataServer.properties
# 普罗米修斯监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  cloud:
    nacos:
      discovery:
        metadata:
          developer: ray
