
defaultDs:
  string:
    url: ${portal.datasource.url}
    username: ${portal.datasource.username}
    password: ${portal.datasource.password}
    driverClassName: ${portal.datasource.driver}
    connection-init-sqls: ${portal.datasource.connection}
    validationQuery: ${portal.datasource.vaildQuery}
    filters: stat
  int:
    initialSize: ${portal.datasource.minSize}
    minIdle: ${portal.datasource.minSize}
    maxActive: ${portal.datasource.maxSize}
    maxPoolPreparedStatementPerConnectionSize: 20
  long:
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  boolean:
    testWhileIdle: true
    testOnBorrow: ${portal.datasource.testOnBorrow}
    testOnReturn: false
    poolPreparedStatements: true




mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml

redxun:
  swagger:
    enabled: true
    title: 门户中心
    description: 门户文档
    version: 1.0
    base-package: com.redxun.portal.core.controller
  cache-manager:
    configs:
      - key: portal
        second: 300
      - key: portal_menu
        second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: portal_tx_group
  enable-auto-data-source-proxy: false

  registry:
    type: nacos
    nacos:
      namespace: ${nacos.namespace:local}
      application: seata-server
      server-addr: ${nacos.address:localhost:8848}
      group: DEFAULT_GROUP
      userName:
      password:

  config:
    type: nacos
    nacos:
      namespace: ${nacos.namespace:local}
      serverAddr: ${nacos.address:localhost:8848}
      group: SEATA_GROUP
      cluster: default
      userName:
      password:
      data-id: seataServer.properties


spring:
  cloud:
    nacos:
      discovery:
        metadata:
          developer: ray
feign:
  compression:
    request:
      enabled: false
    response:
      enabled: false