create user jpaas_form identified by jpaas_form;
create user jpaas_bpm identified by jpaas_bpm;
create user jpaas_system identified by jpaas_system;
create user jpaas_user identified by jpaas_user;
create user jpaas_portal identified by jpaas_portal;
create user jpaas_ureport identified by jpaas_ureport;
create user jpaas_seata identified by jpaas_seata;
create user jpaas_job identified by jpaas_job;
create user jpaas_oa identified by jpaas_oa;
create user jpaas_datart identified by jpaas_datart;

grant connect,dba to jpaas_form;
grant connect,dba to jpaas_bpm;
grant connect,dba to jpaas_system;
grant connect,dba to jpaas_user;
grant connect,dba to jpaas_portal;
grant connect,dba to jpaas_ureport;
grant connect,dba to jpaas_seata;
grant connect,dba to jpaas_job;
grant connect,dba to jpaas_oa;
grant connect,dba to jpaas_datart;