/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Created on:     2022-07-28 14:59:34                          */
/*==============================================================*/


/*==============================================================*/
/* Table: ACCESS_LOG                                            */
/*==============================================================*/
CREATE TABLE ACCESS_LOG 
(
   ID                   VARCHAR2(32)         NOT NULL,
   "USER"               VARCHAR2(32)         NOT NULL,
   RESOURCE_TYPE        VARCHAR2(32),
   RESOURCE_ID          VARCHAR2(32)         NOT NULL,
   ACCESS_TYPE          VARCHAR2(32)         NOT NULL,
   ACCESS_TIME          TIMESTAMP,
   DURATION             INTEGER,
   CONSTRAINT PK_ACCESS_LOG PRIMARY KEY (ID)
);

COMMENT ON TABLE ACCESS_LOG IS
'ACCESS_LOG';

COMMENT ON COLUMN ACCESS_LOG.ID IS
'ID';

COMMENT ON COLUMN ACCESS_LOG."USER" IS
'USER';

COMMENT ON COLUMN ACCESS_LOG.RESOURCE_TYPE IS
'RESOURCE_TYPE';

COMMENT ON COLUMN ACCESS_LOG.RESOURCE_ID IS
'RESOURCE_ID';

COMMENT ON COLUMN ACCESS_LOG.ACCESS_TYPE IS
'ACCESS_TYPE';

COMMENT ON COLUMN ACCESS_LOG.ACCESS_TIME IS
'ACCESS_TIME';

COMMENT ON COLUMN ACCESS_LOG.DURATION IS
'DURATION';

/*==============================================================*/
/* Table: DASHBOARD                                             */
/*==============================================================*/
CREATE TABLE DASHBOARD 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   CONFIG               CLOB,
   THUMBNAIL            VARCHAR2(255),
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_DASHBOARD PRIMARY KEY (ID)
);

COMMENT ON TABLE DASHBOARD IS
'DASHBOARD';

COMMENT ON COLUMN DASHBOARD.ID IS
'ID';

COMMENT ON COLUMN DASHBOARD.NAME IS
'NAME';

COMMENT ON COLUMN DASHBOARD.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN DASHBOARD.CONFIG IS
'CONFIG';

COMMENT ON COLUMN DASHBOARD.THUMBNAIL IS
'THUMBNAIL';

COMMENT ON COLUMN DASHBOARD.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN DASHBOARD.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN DASHBOARD.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN DASHBOARD.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN DASHBOARD.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: DASHBOARD_COPY1                                       */
/*==============================================================*/
CREATE TABLE DASHBOARD_COPY1 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   CONFIG               CLOB,
   THUMBNAIL            VARCHAR2(255),
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_DASHBOARD_COPY1 PRIMARY KEY (ID)
);

COMMENT ON TABLE DASHBOARD_COPY1 IS
'DASHBOARD_COPY1';

COMMENT ON COLUMN DASHBOARD_COPY1.ID IS
'ID';

COMMENT ON COLUMN DASHBOARD_COPY1.NAME IS
'NAME';

COMMENT ON COLUMN DASHBOARD_COPY1.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN DASHBOARD_COPY1.CONFIG IS
'CONFIG';

COMMENT ON COLUMN DASHBOARD_COPY1.THUMBNAIL IS
'THUMBNAIL';

COMMENT ON COLUMN DASHBOARD_COPY1.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN DASHBOARD_COPY1.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN DASHBOARD_COPY1.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN DASHBOARD_COPY1.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN DASHBOARD_COPY1.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: DATACHART                                             */
/*==============================================================*/
CREATE TABLE DATACHART 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   DESCRIPTION          VARCHAR2(255),
   VIEW_ID              VARCHAR2(32),
   ORG_ID               VARCHAR2(32)         NOT NULL,
   CONFIG               CLOB,
   THUMBNAIL            VARCHAR2(255),
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   STATUS               SMALLINT,
   CONSTRAINT PK_DATACHART PRIMARY KEY (ID)
);

COMMENT ON TABLE DATACHART IS
'DATACHART';

COMMENT ON COLUMN DATACHART.ID IS
'ID';

COMMENT ON COLUMN DATACHART.NAME IS
'NAME';

COMMENT ON COLUMN DATACHART.DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN DATACHART.VIEW_ID IS
'VIEW_ID';

COMMENT ON COLUMN DATACHART.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN DATACHART.CONFIG IS
'CONFIG';

COMMENT ON COLUMN DATACHART.THUMBNAIL IS
'THUMBNAIL';

COMMENT ON COLUMN DATACHART.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN DATACHART.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN DATACHART.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN DATACHART.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN DATACHART.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: DOWNLOAD                                              */
/*==============================================================*/
CREATE TABLE DOWNLOAD 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   PATH                 VARCHAR2(512),
   LAST_DOWNLOAD_TIME   TIMESTAMP,
   CREATE_TIME          TIMESTAMP,
   CREATE_BY            VARCHAR2(128)        NOT NULL,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_DOWNLOAD PRIMARY KEY (ID)
);

COMMENT ON TABLE DOWNLOAD IS
'DOWNLOAD';

COMMENT ON COLUMN DOWNLOAD.ID IS
'ID';

COMMENT ON COLUMN DOWNLOAD.NAME IS
'NAME';

COMMENT ON COLUMN DOWNLOAD.PATH IS
'PATH';

COMMENT ON COLUMN DOWNLOAD.LAST_DOWNLOAD_TIME IS
'LAST_DOWNLOAD_TIME';

COMMENT ON COLUMN DOWNLOAD.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN DOWNLOAD.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN DOWNLOAD.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: FOLDER                                                */
/*==============================================================*/
CREATE TABLE FOLDER 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   REL_TYPE             VARCHAR2(255)        NOT NULL,
   SUB_TYPE             VARCHAR2(255),
   REL_ID               VARCHAR2(32),
   AVATAR               VARCHAR2(255),
   PARENT_ID            VARCHAR2(32),
   "INDEX"              BINARY_DOUBLE,
   CONSTRAINT PK_FOLDER PRIMARY KEY (ID)
);

COMMENT ON TABLE FOLDER IS
'FOLDER';

COMMENT ON COLUMN FOLDER.ID IS
'ID';

COMMENT ON COLUMN FOLDER.NAME IS
'NAME';

COMMENT ON COLUMN FOLDER.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN FOLDER.REL_TYPE IS
'REL_TYPE';

COMMENT ON COLUMN FOLDER.SUB_TYPE IS
'SUB_TYPE';

COMMENT ON COLUMN FOLDER.REL_ID IS
'REL_ID';

COMMENT ON COLUMN FOLDER.AVATAR IS
'AVATAR';

COMMENT ON COLUMN FOLDER.PARENT_ID IS
'PARENT_ID';

COMMENT ON COLUMN FOLDER."INDEX" IS
'INDEX';

/*==============================================================*/
/* Table: LINK                                                  */
/*==============================================================*/
CREATE TABLE LINK 
(
   ID                   VARCHAR2(32)         NOT NULL,
   REL_TYPE             VARCHAR2(128)        NOT NULL,
   REL_ID               VARCHAR2(32)         NOT NULL,
   URL                  VARCHAR2(255)        NOT NULL,
   EXPIRATION           TIMESTAMP            NOT NULL,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   CONSTRAINT PK_LINK PRIMARY KEY (ID)
);

COMMENT ON TABLE LINK IS
'LINK';

COMMENT ON COLUMN LINK.ID IS
'ID';

COMMENT ON COLUMN LINK.REL_TYPE IS
'REL_TYPE';

COMMENT ON COLUMN LINK.REL_ID IS
'REL_ID';

COMMENT ON COLUMN LINK.URL IS
'URL';

COMMENT ON COLUMN LINK.EXPIRATION IS
'EXPIRATION';

COMMENT ON COLUMN LINK.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN LINK.CREATE_TIME IS
'CREATE_TIME';

/*==============================================================*/
/* Table: ORGANIZATION                                          */
/*==============================================================*/
CREATE TABLE ORGANIZATION 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   AVATAR               VARCHAR2(255),
   DESCRIPTION          CLOB,
   CREATE_TIME          TIMESTAMP,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   UPDATE_TIME          DATE,
   UPDATE_BY            VARCHAR2(32),
   CONSTRAINT PK_ORGANIZATION PRIMARY KEY (ID)
);

COMMENT ON TABLE ORGANIZATION IS
'ORGANIZATION';

COMMENT ON COLUMN ORGANIZATION.ID IS
'ID';

COMMENT ON COLUMN ORGANIZATION.NAME IS
'NAME';

COMMENT ON COLUMN ORGANIZATION.AVATAR IS
'AVATAR';

COMMENT ON COLUMN ORGANIZATION.DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN ORGANIZATION.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN ORGANIZATION.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN ORGANIZATION.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN ORGANIZATION.UPDATE_BY IS
'UPDATE_BY';

/*==============================================================*/
/* Table: ORG_SETTINGS                                          */
/*==============================================================*/
CREATE TABLE ORG_SETTINGS 
(
   ID                   VARCHAR2(32)         NOT NULL,
   ORG_ID               VARCHAR2(32),
   TYPE                 VARCHAR2(128),
   CONFIG               CLOB,
   CONSTRAINT PK_ORG_SETTINGS PRIMARY KEY (ID)
);

COMMENT ON TABLE ORG_SETTINGS IS
'ORG_SETTINGS';

COMMENT ON COLUMN ORG_SETTINGS.ID IS
'ID';

COMMENT ON COLUMN ORG_SETTINGS.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN ORG_SETTINGS.TYPE IS
'TYPE';

COMMENT ON COLUMN ORG_SETTINGS.CONFIG IS
'CONFIG';

/*==============================================================*/
/* Table: QRTZ_BLOB_TRIGGERS                                    */
/*==============================================================*/
CREATE TABLE QRTZ_BLOB_TRIGGERS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   TRIGGER_NAME         VARCHAR2(200)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   BLOB_DATA            BLOB,
   CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_BLOB_TRIGGERS IS
'QRTZ_BLOB_TRIGGERS';

COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.TRIGGER_NAME IS
'TRIGGER_NAME';

COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

COMMENT ON COLUMN QRTZ_BLOB_TRIGGERS.BLOB_DATA IS
'BLOB_DATA';

/*==============================================================*/
/* Table: QRTZ_CALENDARS                                        */
/*==============================================================*/
CREATE TABLE QRTZ_CALENDARS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   CALENDAR_NAME        VARCHAR2(200)        NOT NULL,
   CALENDAR             BLOB                 NOT NULL,
   CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

COMMENT ON TABLE QRTZ_CALENDARS IS
'QRTZ_CALENDARS';

COMMENT ON COLUMN QRTZ_CALENDARS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_CALENDARS.CALENDAR_NAME IS
'CALENDAR_NAME';

COMMENT ON COLUMN QRTZ_CALENDARS.CALENDAR IS
'CALENDAR';

/*==============================================================*/
/* Table: QRTZ_CRON_TRIGGERS                                    */
/*==============================================================*/
CREATE TABLE QRTZ_CRON_TRIGGERS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   TRIGGER_NAME         VARCHAR2(200)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   CRON_EXPRESSION      VARCHAR2(200)        NOT NULL,
   TIME_ZONE_ID         VARCHAR2(80),
   CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_CRON_TRIGGERS IS
'QRTZ_CRON_TRIGGERS';

COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.TRIGGER_NAME IS
'TRIGGER_NAME';

COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.CRON_EXPRESSION IS
'CRON_EXPRESSION';

COMMENT ON COLUMN QRTZ_CRON_TRIGGERS.TIME_ZONE_ID IS
'TIME_ZONE_ID';

/*==============================================================*/
/* Table: QRTZ_FIRED_TRIGGERS                                   */
/*==============================================================*/
CREATE TABLE QRTZ_FIRED_TRIGGERS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   ENTRY_ID             VARCHAR2(95)         NOT NULL,
   TRIGGER_NAME         VARCHAR2(200)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   INSTANCE_NAME        VARCHAR2(200)        NOT NULL,
   FIRED_TIME           INTEGER              NOT NULL,
   SCHED_TIME           INTEGER              NOT NULL,
   PRIORITY             INTEGER              NOT NULL,
   STATE                VARCHAR2(16)         NOT NULL,
   JOB_NAME             VARCHAR2(200),
   JOB_GROUP            VARCHAR2(200),
   IS_NONCONCURRENT     VARCHAR2(1),
   REQUESTS_RECOVERY    VARCHAR2(1),
   CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

COMMENT ON TABLE QRTZ_FIRED_TRIGGERS IS
'QRTZ_FIRED_TRIGGERS';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.ENTRY_ID IS
'ENTRY_ID';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.TRIGGER_NAME IS
'TRIGGER_NAME';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.INSTANCE_NAME IS
'INSTANCE_NAME';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.FIRED_TIME IS
'FIRED_TIME';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.SCHED_TIME IS
'SCHED_TIME';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.PRIORITY IS
'PRIORITY';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.STATE IS
'STATE';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.JOB_NAME IS
'JOB_NAME';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.JOB_GROUP IS
'JOB_GROUP';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.IS_NONCONCURRENT IS
'IS_NONCONCURRENT';

COMMENT ON COLUMN QRTZ_FIRED_TRIGGERS.REQUESTS_RECOVERY IS
'REQUESTS_RECOVERY';

/*==============================================================*/
/* Table: QRTZ_JOB_DETAILS                                      */
/*==============================================================*/
CREATE TABLE QRTZ_JOB_DETAILS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   JOB_NAME             VARCHAR2(200)        NOT NULL,
   JOB_GROUP            VARCHAR2(200)        NOT NULL,
   DESCRIPTION          VARCHAR2(250),
   JOB_CLASS_NAME       VARCHAR2(250)        NOT NULL,
   IS_DURABLE           VARCHAR2(1)          NOT NULL,
   IS_NONCONCURRENT     VARCHAR2(1)          NOT NULL,
   IS_UPDATE_DATA       VARCHAR2(1)          NOT NULL,
   REQUESTS_RECOVERY    VARCHAR2(1)          NOT NULL,
   JOB_DATA             BLOB,
   CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

COMMENT ON TABLE QRTZ_JOB_DETAILS IS
'QRTZ_JOB_DETAILS';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_NAME IS
'JOB_NAME';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_GROUP IS
'JOB_GROUP';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_CLASS_NAME IS
'JOB_CLASS_NAME';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.IS_DURABLE IS
'IS_DURABLE';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.IS_NONCONCURRENT IS
'IS_NONCONCURRENT';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.IS_UPDATE_DATA IS
'IS_UPDATE_DATA';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.REQUESTS_RECOVERY IS
'REQUESTS_RECOVERY';

COMMENT ON COLUMN QRTZ_JOB_DETAILS.JOB_DATA IS
'JOB_DATA';

/*==============================================================*/
/* Table: QRTZ_LOCKS                                            */
/*==============================================================*/
CREATE TABLE QRTZ_LOCKS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   LOCK_NAME            VARCHAR2(40)         NOT NULL,
   CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

COMMENT ON TABLE QRTZ_LOCKS IS
'QRTZ_LOCKS';

COMMENT ON COLUMN QRTZ_LOCKS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_LOCKS.LOCK_NAME IS
'LOCK_NAME';

/*==============================================================*/
/* Table: QRTZ_PAUSED_TRIGGER_GRPS                              */
/*==============================================================*/
CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_PAUSED_TRIGGER_GRPS IS
'QRTZ_PAUSED_TRIGGER_GRPS';

COMMENT ON COLUMN QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

/*==============================================================*/
/* Table: QRTZ_SCHEDULER_STATE                                  */
/*==============================================================*/
CREATE TABLE QRTZ_SCHEDULER_STATE 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   INSTANCE_NAME        VARCHAR2(200)        NOT NULL,
   LAST_CHECKIN_TIME    INTEGER              NOT NULL,
   CHECKIN_INTERVAL     INTEGER              NOT NULL,
   CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

COMMENT ON TABLE QRTZ_SCHEDULER_STATE IS
'QRTZ_SCHEDULER_STATE';

COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.INSTANCE_NAME IS
'INSTANCE_NAME';

COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME IS
'LAST_CHECKIN_TIME';

COMMENT ON COLUMN QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL IS
'CHECKIN_INTERVAL';

/*==============================================================*/
/* Table: QRTZ_SIMPLE_TRIGGERS                                  */
/*==============================================================*/
CREATE TABLE QRTZ_SIMPLE_TRIGGERS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   TRIGGER_NAME         VARCHAR2(200)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   REPEAT_COUNT         INTEGER              NOT NULL,
   REPEAT_INTERVAL      INTEGER              NOT NULL,
   TIMES_TRIGGERED      INTEGER              NOT NULL,
   CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_SIMPLE_TRIGGERS IS
'QRTZ_SIMPLE_TRIGGERS';

COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.REPEAT_COUNT IS
'REPEAT_COUNT';

COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.REPEAT_INTERVAL IS
'REPEAT_INTERVAL';

COMMENT ON COLUMN QRTZ_SIMPLE_TRIGGERS.TIMES_TRIGGERED IS
'TIMES_TRIGGERED';

/*==============================================================*/
/* Table: QRTZ_SIMPROP_TRIGGERS                                 */
/*==============================================================*/
CREATE TABLE QRTZ_SIMPROP_TRIGGERS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   TRIGGER_NAME         VARCHAR2(200)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   STR_PROP_1           VARCHAR2(512),
   STR_PROP_2           VARCHAR2(512),
   STR_PROP_3           VARCHAR2(512),
   INT_PROP_1           INTEGER,
   INT_PROP_2           INTEGER,
   LONG_PROP_1          INTEGER,
   LONG_PROP_2          INTEGER,
   DEC_PROP_1           NUMBER(13,4),
   DEC_PROP_2           NUMBER(13,4),
   BOOL_PROP_1          VARCHAR2(1),
   BOOL_PROP_2          VARCHAR2(1),
   CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_SIMPROP_TRIGGERS IS
'QRTZ_SIMPROP_TRIGGERS';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.TRIGGER_NAME IS
'TRIGGER_NAME';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.STR_PROP_1 IS
'STR_PROP_1';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.STR_PROP_2 IS
'STR_PROP_2';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.STR_PROP_3 IS
'STR_PROP_3';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.INT_PROP_1 IS
'INT_PROP_1';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.INT_PROP_2 IS
'INT_PROP_2';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.LONG_PROP_1 IS
'LONG_PROP_1';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.LONG_PROP_2 IS
'LONG_PROP_2';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.DEC_PROP_1 IS
'DEC_PROP_1';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.DEC_PROP_2 IS
'DEC_PROP_2';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_1 IS
'BOOL_PROP_1';

COMMENT ON COLUMN QRTZ_SIMPROP_TRIGGERS.BOOL_PROP_2 IS
'BOOL_PROP_2';

/*==============================================================*/
/* Table: QRTZ_TRIGGERS                                         */
/*==============================================================*/
CREATE TABLE QRTZ_TRIGGERS 
(
   SCHED_NAME           VARCHAR2(120)        NOT NULL,
   TRIGGER_NAME         VARCHAR2(200)        NOT NULL,
   TRIGGER_GROUP        VARCHAR2(200)        NOT NULL,
   JOB_NAME             VARCHAR2(200)        NOT NULL,
   JOB_GROUP            VARCHAR2(200)        NOT NULL,
   DESCRIPTION          VARCHAR2(250),
   NEXT_FIRE_TIME       INTEGER,
   PREV_FIRE_TIME       INTEGER,
   PRIORITY             INTEGER,
   TRIGGER_STATE        VARCHAR2(16)         NOT NULL,
   TRIGGER_TYPE         VARCHAR2(8)          NOT NULL,
   START_TIME           INTEGER              NOT NULL,
   END_TIME             INTEGER,
   CALENDAR_NAME        VARCHAR2(200),
   MISFIRE_INSTR        SMALLINT,
   JOB_DATA             BLOB,
   CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);

COMMENT ON TABLE QRTZ_TRIGGERS IS
'QRTZ_TRIGGERS';

COMMENT ON COLUMN QRTZ_TRIGGERS.SCHED_NAME IS
'SCHED_NAME';

COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_NAME IS
'TRIGGER_NAME';

COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_GROUP IS
'TRIGGER_GROUP';

COMMENT ON COLUMN QRTZ_TRIGGERS.JOB_NAME IS
'JOB_NAME';

COMMENT ON COLUMN QRTZ_TRIGGERS.JOB_GROUP IS
'JOB_GROUP';

COMMENT ON COLUMN QRTZ_TRIGGERS.DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN QRTZ_TRIGGERS.NEXT_FIRE_TIME IS
'NEXT_FIRE_TIME';

COMMENT ON COLUMN QRTZ_TRIGGERS.PREV_FIRE_TIME IS
'PREV_FIRE_TIME';

COMMENT ON COLUMN QRTZ_TRIGGERS.PRIORITY IS
'PRIORITY';

COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_STATE IS
'TRIGGER_STATE';

COMMENT ON COLUMN QRTZ_TRIGGERS.TRIGGER_TYPE IS
'TRIGGER_TYPE';

COMMENT ON COLUMN QRTZ_TRIGGERS.START_TIME IS
'START_TIME';

COMMENT ON COLUMN QRTZ_TRIGGERS.END_TIME IS
'END_TIME';

COMMENT ON COLUMN QRTZ_TRIGGERS.CALENDAR_NAME IS
'CALENDAR_NAME';

COMMENT ON COLUMN QRTZ_TRIGGERS.MISFIRE_INSTR IS
'MISFIRE_INSTR';

COMMENT ON COLUMN QRTZ_TRIGGERS.JOB_DATA IS
'JOB_DATA';

/*==============================================================*/
/* Table: REL_ROLE_RESOURCE                                     */
/*==============================================================*/
CREATE TABLE REL_ROLE_RESOURCE 
(
   ID                   VARCHAR2(32)         NOT NULL,
   ROLE_ID              VARCHAR2(32)         NOT NULL,
   RESOURCE_ID          VARCHAR2(32),
   RESOURCE_TYPE        VARCHAR2(100)        NOT NULL,
   ORG_ID               VARCHAR2(32),
   PERMISSION           INTEGER              NOT NULL,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   CONSTRAINT PK_REL_ROLE_RESOURCE PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_ROLE_RESOURCE IS
'REL_ROLE_RESOURCE';

COMMENT ON COLUMN REL_ROLE_RESOURCE.ID IS
'ID';

COMMENT ON COLUMN REL_ROLE_RESOURCE.ROLE_ID IS
'ROLE_ID';

COMMENT ON COLUMN REL_ROLE_RESOURCE.RESOURCE_ID IS
'RESOURCE_ID';

COMMENT ON COLUMN REL_ROLE_RESOURCE.RESOURCE_TYPE IS
'RESOURCE_TYPE';

COMMENT ON COLUMN REL_ROLE_RESOURCE.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN REL_ROLE_RESOURCE.PERMISSION IS
'PERMISSION';

COMMENT ON COLUMN REL_ROLE_RESOURCE.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN REL_ROLE_RESOURCE.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN REL_ROLE_RESOURCE.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN REL_ROLE_RESOURCE.UPDATE_TIME IS
'UPDATE_TIME';

/*==============================================================*/
/* Table: REL_ROLE_USER                                         */
/*==============================================================*/
CREATE TABLE REL_ROLE_USER 
(
   ID                   VARCHAR2(32)         NOT NULL,
   USER_ID              VARCHAR2(32)         NOT NULL,
   ROLE_ID              VARCHAR2(32)         NOT NULL,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   COLUMN_8             CHAR(10),
   CONSTRAINT PK_REL_ROLE_USER PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_ROLE_USER IS
'REL_ROLE_USER';

COMMENT ON COLUMN REL_ROLE_USER.ID IS
'ID';

COMMENT ON COLUMN REL_ROLE_USER.USER_ID IS
'USER_ID';

COMMENT ON COLUMN REL_ROLE_USER.ROLE_ID IS
'ROLE_ID';

COMMENT ON COLUMN REL_ROLE_USER.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN REL_ROLE_USER.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN REL_ROLE_USER.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN REL_ROLE_USER.UPDATE_TIME IS
'UPDATE_TIME';

/*==============================================================*/
/* Table: REL_SUBJECT_COLUMNS                                   */
/*==============================================================*/
CREATE TABLE REL_SUBJECT_COLUMNS 
(
   ID                   VARCHAR2(32)         NOT NULL,
   VIEW_ID              VARCHAR2(32)         NOT NULL,
   SUBJECT_ID           VARCHAR2(32)         NOT NULL,
   SUBJECT_TYPE         VARCHAR2(32)         NOT NULL,
   COLUMN_PERMISSION    CLOB,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   CONSTRAINT PK_REL_SUBJECT_COLUMNS PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_SUBJECT_COLUMNS IS
'REL_SUBJECT_COLUMNS';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.ID IS
'ID';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.VIEW_ID IS
'VIEW_ID';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.SUBJECT_ID IS
'SUBJECT_ID';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.SUBJECT_TYPE IS
'SUBJECT_TYPE';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.COLUMN_PERMISSION IS
'COLUMN_PERMISSION';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN REL_SUBJECT_COLUMNS.UPDATE_TIME IS
'UPDATE_TIME';

/*==============================================================*/
/* Table: REL_USER_ORGANIZATION                                 */
/*==============================================================*/
CREATE TABLE REL_USER_ORGANIZATION 
(
   ID                   VARCHAR2(32)         NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   USER_ID              VARCHAR2(32)         NOT NULL,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   CONSTRAINT PK_REL_USER_ORGANIZATION PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_USER_ORGANIZATION IS
'REL_USER_ORGANIZATION';

COMMENT ON COLUMN REL_USER_ORGANIZATION.ID IS
'ID';

COMMENT ON COLUMN REL_USER_ORGANIZATION.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN REL_USER_ORGANIZATION.USER_ID IS
'USER_ID';

COMMENT ON COLUMN REL_USER_ORGANIZATION.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN REL_USER_ORGANIZATION.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN REL_USER_ORGANIZATION.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN REL_USER_ORGANIZATION.UPDATE_TIME IS
'UPDATE_TIME';

/*==============================================================*/
/* Table: REL_VARIABLE_SUBJECT                                  */
/*==============================================================*/
CREATE TABLE REL_VARIABLE_SUBJECT 
(
   ID                   VARCHAR2(32)         NOT NULL,
   VARIABLE_ID          VARCHAR2(32)         NOT NULL,
   SUBJECT_ID           VARCHAR2(32)         NOT NULL,
   SUBJECT_TYPE         VARCHAR2(32)         NOT NULL,
   VALUE                VARCHAR2(255),
   CREATE_TIME          TIMESTAMP,
   USE_DEFAULT_VALUE    SMALLINT             NOT NULL,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   UPDATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   CONSTRAINT PK_REL_VARIABLE_SUBJECT PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_VARIABLE_SUBJECT IS
'REL_VARIABLE_SUBJECT';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.ID IS
'ID';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.VARIABLE_ID IS
'VARIABLE_ID';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.SUBJECT_ID IS
'SUBJECT_ID';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.SUBJECT_TYPE IS
'SUBJECT_TYPE';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.VALUE IS
'VALUE';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.USE_DEFAULT_VALUE IS
'USE_DEFAULT_VALUE';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN REL_VARIABLE_SUBJECT.UPDATE_BY IS
'UPDATE_BY';

/*==============================================================*/
/* Table: REL_WIDGET_ELEMENT                                    */
/*==============================================================*/
CREATE TABLE REL_WIDGET_ELEMENT 
(
   ID                   VARCHAR2(32)         NOT NULL,
   WIDGET_ID            VARCHAR2(32)         NOT NULL,
   REL_TYPE             VARCHAR2(32)         NOT NULL,
   REL_ID               VARCHAR2(32)         NOT NULL,
   CONSTRAINT PK_REL_WIDGET_ELEMENT PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_WIDGET_ELEMENT IS
'REL_WIDGET_ELEMENT';

COMMENT ON COLUMN REL_WIDGET_ELEMENT.ID IS
'ID';

COMMENT ON COLUMN REL_WIDGET_ELEMENT.WIDGET_ID IS
'WIDGET_ID';

COMMENT ON COLUMN REL_WIDGET_ELEMENT.REL_TYPE IS
'REL_TYPE';

COMMENT ON COLUMN REL_WIDGET_ELEMENT.REL_ID IS
'REL_ID';

/*==============================================================*/
/* Table: REL_WIDGET_WIDGET                                     */
/*==============================================================*/
CREATE TABLE REL_WIDGET_WIDGET 
(
   ID                   VARCHAR2(32)         NOT NULL,
   SOURCE_ID            VARCHAR2(32)         NOT NULL,
   TARGET_ID            VARCHAR2(32)         NOT NULL,
   CONFIG               CLOB,
   CONSTRAINT PK_REL_WIDGET_WIDGET PRIMARY KEY (ID)
);

COMMENT ON TABLE REL_WIDGET_WIDGET IS
'REL_WIDGET_WIDGET';

COMMENT ON COLUMN REL_WIDGET_WIDGET.ID IS
'ID';

COMMENT ON COLUMN REL_WIDGET_WIDGET.SOURCE_ID IS
'SOURCE_ID';

COMMENT ON COLUMN REL_WIDGET_WIDGET.TARGET_ID IS
'TARGET_ID';

COMMENT ON COLUMN REL_WIDGET_WIDGET.CONFIG IS
'CONFIG';

/*==============================================================*/
/* Table: ROLE                                                  */
/*==============================================================*/
CREATE TABLE ROLE 
(
   ID                   VARCHAR2(32)         NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   TYPE                 VARCHAR2(16),
   DESCRIPTION          VARCHAR2(255),
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   AVATAR               VARCHAR2(255),
   CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

COMMENT ON TABLE ROLE IS
'ROLE';

COMMENT ON COLUMN ROLE.ID IS
'ID';

COMMENT ON COLUMN ROLE.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN ROLE.NAME IS
'NAME';

COMMENT ON COLUMN ROLE.TYPE IS
'TYPE';

COMMENT ON COLUMN ROLE.DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN ROLE.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN ROLE.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN ROLE.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN ROLE.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN ROLE.AVATAR IS
'AVATAR';

/*==============================================================*/
/* Table: SCHEDULE                                              */
/*==============================================================*/
CREATE TABLE SCHEDULE 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   TYPE                 VARCHAR2(100)        NOT NULL,
   ACTIVE               SMALLINT             NOT NULL,
   CRON_EXPRESSION      VARCHAR2(100),
   START_DATE           TIMESTAMP,
   END_DATE             TIMESTAMP,
   CONFIG               CLOB,
   CREATE_TIME          TIMESTAMP,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   PARENT_ID            VARCHAR2(32),
   IS_FOLDER            SMALLINT,
   "INDEX"              BINARY_DOUBLE,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_SCHEDULE PRIMARY KEY (ID)
);

COMMENT ON TABLE SCHEDULE IS
'SCHEDULE';

COMMENT ON COLUMN SCHEDULE.ID IS
'ID';

COMMENT ON COLUMN SCHEDULE.NAME IS
'NAME';

COMMENT ON COLUMN SCHEDULE.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN SCHEDULE.TYPE IS
'TYPE';

COMMENT ON COLUMN SCHEDULE.ACTIVE IS
'ACTIVE';

COMMENT ON COLUMN SCHEDULE.CRON_EXPRESSION IS
'CRON_EXPRESSION';

COMMENT ON COLUMN SCHEDULE.START_DATE IS
'START_DATE';

COMMENT ON COLUMN SCHEDULE.END_DATE IS
'END_DATE';

COMMENT ON COLUMN SCHEDULE.CONFIG IS
'CONFIG';

COMMENT ON COLUMN SCHEDULE.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN SCHEDULE.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN SCHEDULE.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN SCHEDULE.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN SCHEDULE.PARENT_ID IS
'PARENT_ID';

COMMENT ON COLUMN SCHEDULE.IS_FOLDER IS
'IS_FOLDER';

COMMENT ON COLUMN SCHEDULE."INDEX" IS
'INDEX';

COMMENT ON COLUMN SCHEDULE.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: SCHEDULE_LOG                                          */
/*==============================================================*/
CREATE TABLE SCHEDULE_LOG 
(
   ID                   VARCHAR2(32)         NOT NULL,
   SCHEDULE_ID          VARCHAR2(32)         NOT NULL,
   "START"              TIMESTAMP,
   END                  TIMESTAMP,
   STATUS               INTEGER              NOT NULL,
   MESSAGE              CLOB,
   CONSTRAINT PK_SCHEDULE_LOG PRIMARY KEY (ID)
);

COMMENT ON TABLE SCHEDULE_LOG IS
'SCHEDULE_LOG';

COMMENT ON COLUMN SCHEDULE_LOG.ID IS
'ID';

COMMENT ON COLUMN SCHEDULE_LOG.SCHEDULE_ID IS
'SCHEDULE_ID';

COMMENT ON COLUMN SCHEDULE_LOG."START" IS
'START';

COMMENT ON COLUMN SCHEDULE_LOG.STATUS IS
'STATUS';

COMMENT ON COLUMN SCHEDULE_LOG.MESSAGE IS
'MESSAGE';

/*==============================================================*/
/* Table: "SHARE"                                               */
/*==============================================================*/
CREATE TABLE "SHARE" 
(
   ID                   VARCHAR2(32)         NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   VIZ_TYPE             VARCHAR2(128)        NOT NULL,
   VIZ_ID               VARCHAR2(32)         NOT NULL,
   AUTHENTICATION_MODE  VARCHAR2(128)        NOT NULL,
   ROLES                CLOB,
   ROW_PERMISSION_BY    VARCHAR2(128)        NOT NULL,
   AUTHENTICATION_CODE  VARCHAR2(255),
   EXPIRY_DATE          TIMESTAMP,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   CONSTRAINT PK_SHARE PRIMARY KEY (ID)
);

COMMENT ON TABLE "SHARE" IS
'SHARE';

COMMENT ON COLUMN "SHARE".ID IS
'ID';

COMMENT ON COLUMN "SHARE".ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN "SHARE".VIZ_TYPE IS
'VIZ_TYPE';

COMMENT ON COLUMN "SHARE".VIZ_ID IS
'VIZ_ID';

COMMENT ON COLUMN "SHARE".AUTHENTICATION_MODE IS
'AUTHENTICATION_MODE';

COMMENT ON COLUMN "SHARE".ROLES IS
'ROLES';

COMMENT ON COLUMN "SHARE".ROW_PERMISSION_BY IS
'ROW_PERMISSION_BY';

COMMENT ON COLUMN "SHARE".AUTHENTICATION_CODE IS
'AUTHENTICATION_CODE';

COMMENT ON COLUMN "SHARE".EXPIRY_DATE IS
'EXPIRY_DATE';

COMMENT ON COLUMN "SHARE".CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN "SHARE".CREATE_TIME IS
'CREATE_TIME';

/*==============================================================*/
/* Table: SOURCE                                                */
/*==============================================================*/
CREATE TABLE SOURCE 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   CONFIG               CLOB,
   TYPE                 VARCHAR2(10)         NOT NULL,
   ORG_ID               VARCHAR2(32),
   PARENT_ID            VARCHAR2(32),
   IS_FOLDER            SMALLINT,
   "INDEX"              BINARY_DOUBLE,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_SOURCE PRIMARY KEY (ID)
);

COMMENT ON TABLE SOURCE IS
'SOURCE';

COMMENT ON COLUMN SOURCE.ID IS
'ID';

COMMENT ON COLUMN SOURCE.NAME IS
'NAME';

COMMENT ON COLUMN SOURCE.CONFIG IS
'CONFIG';

COMMENT ON COLUMN SOURCE.TYPE IS
'TYPE';

COMMENT ON COLUMN SOURCE.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN SOURCE.PARENT_ID IS
'PARENT_ID';

COMMENT ON COLUMN SOURCE.IS_FOLDER IS
'IS_FOLDER';

COMMENT ON COLUMN SOURCE."INDEX" IS
'INDEX';

COMMENT ON COLUMN SOURCE.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN SOURCE.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN SOURCE.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN SOURCE.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN SOURCE.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: SOURCE_SCHEMAS                                        */
/*==============================================================*/
CREATE TABLE SOURCE_SCHEMAS 
(
   ID                   VARCHAR2(32)         NOT NULL,
   SOURCE_ID            VARCHAR2(32)         NOT NULL,
   SCHEMAS              CLOB,
   UPDATE_TIME          DATE,
   CONSTRAINT PK_SOURCE_SCHEMAS PRIMARY KEY (ID)
);

COMMENT ON TABLE SOURCE_SCHEMAS IS
'SOURCE_SCHEMAS';

COMMENT ON COLUMN SOURCE_SCHEMAS.ID IS
'ID';

COMMENT ON COLUMN SOURCE_SCHEMAS.SOURCE_ID IS
'SOURCE_ID';

COMMENT ON COLUMN SOURCE_SCHEMAS.SCHEMAS IS
'SCHEMAS';

COMMENT ON COLUMN SOURCE_SCHEMAS.UPDATE_TIME IS
'UPDATE_TIME';

/*==============================================================*/
/* Table: STORYBOARD                                            */
/*==============================================================*/
CREATE TABLE STORYBOARD 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   PARENT_ID            VARCHAR2(32),
   IS_FOLDER            SMALLINT,
   "INDEX"              BINARY_DOUBLE,
   CONFIG               CLOB,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_STORYBOARD PRIMARY KEY (ID)
);

COMMENT ON TABLE STORYBOARD IS
'STORYBOARD';

COMMENT ON COLUMN STORYBOARD.ID IS
'ID';

COMMENT ON COLUMN STORYBOARD.NAME IS
'NAME';

COMMENT ON COLUMN STORYBOARD.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN STORYBOARD.PARENT_ID IS
'PARENT_ID';

COMMENT ON COLUMN STORYBOARD.IS_FOLDER IS
'IS_FOLDER';

COMMENT ON COLUMN STORYBOARD."INDEX" IS
'INDEX';

COMMENT ON COLUMN STORYBOARD.CONFIG IS
'CONFIG';

COMMENT ON COLUMN STORYBOARD.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN STORYBOARD.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN STORYBOARD.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN STORYBOARD.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN STORYBOARD.STATUS IS
'STATUS';

/*==============================================================*/
/* Table: STORYPAGE                                             */
/*==============================================================*/
CREATE TABLE STORYPAGE 
(
   ID                   VARCHAR2(32)         NOT NULL,
   STORYBOARD_ID        VARCHAR2(32)         NOT NULL,
   REL_TYPE             VARCHAR2(128)        NOT NULL,
   REL_ID               VARCHAR2(32)         NOT NULL,
   CONFIG               CLOB,
   CONSTRAINT PK_STORYPAGE PRIMARY KEY (ID)
);

COMMENT ON TABLE STORYPAGE IS
'STORYPAGE';

COMMENT ON COLUMN STORYPAGE.ID IS
'ID';

COMMENT ON COLUMN STORYPAGE.STORYBOARD_ID IS
'STORYBOARD_ID';

COMMENT ON COLUMN STORYPAGE.REL_TYPE IS
'REL_TYPE';

COMMENT ON COLUMN STORYPAGE.REL_ID IS
'REL_ID';

COMMENT ON COLUMN STORYPAGE.CONFIG IS
'CONFIG';

/*==============================================================*/
/* Table: "USER"                                                */
/*==============================================================*/
CREATE TABLE "USER" 
(
   ID                   VARCHAR2(32)         NOT NULL,
   EMAIL                VARCHAR2(255)        NOT NULL,
   USERNAME             VARCHAR2(255)        NOT NULL,
   PASSWORD             VARCHAR2(255)        NOT NULL,
   ACTIVE               SMALLINT,
   NAME                 VARCHAR2(255),
   DESCRIPTION          VARCHAR2(255),
   AVATAR               VARCHAR2(255),
   CREATE_TIME          TIMESTAMP,
   CREATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   CONSTRAINT PK_USER PRIMARY KEY (ID)
);

COMMENT ON TABLE "USER" IS
'USER';

COMMENT ON COLUMN "USER".ID IS
'ID';

COMMENT ON COLUMN "USER".EMAIL IS
'EMAIL';

COMMENT ON COLUMN "USER".USERNAME IS
'USERNAME';

COMMENT ON COLUMN "USER".PASSWORD IS
'PASSWORD';

COMMENT ON COLUMN "USER".ACTIVE IS
'ACTIVE';

COMMENT ON COLUMN "USER".NAME IS
'NAME';

COMMENT ON COLUMN "USER".DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN "USER".AVATAR IS
'AVATAR';

COMMENT ON COLUMN "USER".CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN "USER".CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN "USER".UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN "USER".UPDATE_BY IS
'UPDATE_BY';

/*==============================================================*/
/* Table: USER_SETTINGS                                         */
/*==============================================================*/
CREATE TABLE USER_SETTINGS 
(
   ID                   VARCHAR2(32)         NOT NULL,
   USER_ID              VARCHAR2(32)         NOT NULL,
   REL_TYPE             VARCHAR2(128)        NOT NULL,
   REL_ID               VARCHAR2(32),
   CONFIG               CLOB,
   CONSTRAINT PK_USER_SETTINGS PRIMARY KEY (ID)
);

COMMENT ON TABLE USER_SETTINGS IS
'USER_SETTINGS';

COMMENT ON COLUMN USER_SETTINGS.ID IS
'ID';

COMMENT ON COLUMN USER_SETTINGS.USER_ID IS
'USER_ID';

COMMENT ON COLUMN USER_SETTINGS.REL_TYPE IS
'REL_TYPE';

COMMENT ON COLUMN USER_SETTINGS.REL_ID IS
'REL_ID';

COMMENT ON COLUMN USER_SETTINGS.CONFIG IS
'CONFIG';

/*==============================================================*/
/* Table: VARIABLE                                              */
/*==============================================================*/
CREATE TABLE VARIABLE 
(
   ID                   VARCHAR2(32)         NOT NULL,
   ORG_ID               VARCHAR2(32)         NOT NULL,
   VIEW_ID              VARCHAR2(32),
   SOURCE_ID            VARCHAR2(32),
   NAME                 VARCHAR2(255)        NOT NULL,
   TYPE                 VARCHAR2(32)         NOT NULL,
   VALUE_TYPE           VARCHAR2(32)         NOT NULL,
   FORMAT               VARCHAR2(255),
   PERMISSION           INTEGER,
   ENCRYPT              SMALLINT,
   LABEL                VARCHAR2(255),
   DEFAULT_VALUE        VARCHAR2(255),
   EXPRESSION           SMALLINT,
   CREATE_TIME          TIMESTAMP,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   UPDATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   CONSTRAINT PK_VARIABLE PRIMARY KEY (ID)
);

COMMENT ON TABLE VARIABLE IS
'VARIABLE';

COMMENT ON COLUMN VARIABLE.ID IS
'ID';

COMMENT ON COLUMN VARIABLE.ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN VARIABLE.VIEW_ID IS
'VIEW_ID';

COMMENT ON COLUMN VARIABLE.SOURCE_ID IS
'SOURCE_ID';

COMMENT ON COLUMN VARIABLE.NAME IS
'NAME';

COMMENT ON COLUMN VARIABLE.TYPE IS
'TYPE';

COMMENT ON COLUMN VARIABLE.VALUE_TYPE IS
'VALUE_TYPE';

COMMENT ON COLUMN VARIABLE.FORMAT IS
'FORMAT';

COMMENT ON COLUMN VARIABLE.PERMISSION IS
'PERMISSION';

COMMENT ON COLUMN VARIABLE.ENCRYPT IS
'ENCRYPT';

COMMENT ON COLUMN VARIABLE.LABEL IS
'LABEL';

COMMENT ON COLUMN VARIABLE.DEFAULT_VALUE IS
'DEFAULT_VALUE';

COMMENT ON COLUMN VARIABLE.EXPRESSION IS
'EXPRESSION';

COMMENT ON COLUMN VARIABLE.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN VARIABLE.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN VARIABLE.UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN VARIABLE.UPDATE_BY IS
'UPDATE_BY';

/*==============================================================*/
/* Index: SOURCE_ID                                             */
/*==============================================================*/
CREATE INDEX SOURCE_ID ON VARIABLE (
   SOURCE_ID ASC
);

/*==============================================================*/
/* Table: "VIEW"                                                */
/*==============================================================*/
CREATE TABLE "VIEW" 
(
   ID                   VARCHAR2(32)         NOT NULL,
   NAME                 VARCHAR2(255)        NOT NULL,
   DESCRIPTION          VARCHAR2(255),
   ORG_ID               VARCHAR2(32)         NOT NULL,
   SOURCE_ID            VARCHAR2(32),
   SCRIPT               CLOB,
   TYPE                 VARCHAR2(32),
   MODEL                CLOB,
   CONFIG               CLOB,
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   PARENT_ID            VARCHAR2(32),
   IS_FOLDER            SMALLINT,
   "INDEX"              BINARY_DOUBLE,
   STATUS               SMALLINT             NOT NULL,
   CONSTRAINT PK_VIEW PRIMARY KEY (ID)
);

COMMENT ON TABLE "VIEW" IS
'VIEW';

COMMENT ON COLUMN "VIEW".ID IS
'ID';

COMMENT ON COLUMN "VIEW".NAME IS
'NAEM';

COMMENT ON COLUMN "VIEW".DESCRIPTION IS
'DESCRIPTION';

COMMENT ON COLUMN "VIEW".ORG_ID IS
'ORG_ID';

COMMENT ON COLUMN "VIEW".SOURCE_ID IS
'SOURCE_ID';

COMMENT ON COLUMN "VIEW".SCRIPT IS
'SCRIPT';

COMMENT ON COLUMN "VIEW".TYPE IS
'TYPE';

COMMENT ON COLUMN "VIEW".MODEL IS
'MODEL';

COMMENT ON COLUMN "VIEW".CONFIG IS
'CONFIG';

COMMENT ON COLUMN "VIEW".CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN "VIEW".CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN "VIEW".UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN "VIEW".UPDATE_TIME IS
'UPDATE_TIME';

COMMENT ON COLUMN "VIEW".PARENT_ID IS
'PARENT_ID';

COMMENT ON COLUMN "VIEW".IS_FOLDER IS
'IS_FOLDER';

COMMENT ON COLUMN "VIEW"."INDEX" IS
'INDEX';

COMMENT ON COLUMN "VIEW".STATUS IS
'STATUS';

/*==============================================================*/
/* Table: WIDGET                                                */
/*==============================================================*/
CREATE TABLE WIDGET 
(
   ID                   VARCHAR2(32)         NOT NULL,
   DASHBOARD_ID         VARCHAR2(32)         NOT NULL,
   CONFIG               CLOB,
   PARENT_ID            VARCHAR2(32),
   CREATE_BY            VARCHAR2(32)         NOT NULL,
   CREATE_TIME          TIMESTAMP,
   UPDATE_BY            VARCHAR2(32),
   UPDATE_TIME          TIMESTAMP,
   CONSTRAINT PK_WIDGET PRIMARY KEY (ID)
);

COMMENT ON TABLE WIDGET IS
'WIDGET';

COMMENT ON COLUMN WIDGET.ID IS
'ID';

COMMENT ON COLUMN WIDGET.DASHBOARD_ID IS
'DASHBOARD_ID';

COMMENT ON COLUMN WIDGET.CONFIG IS
'CONFIG';

COMMENT ON COLUMN WIDGET.PARENT_ID IS
'PARENT_ID';

COMMENT ON COLUMN WIDGET.CREATE_BY IS
'CREATE_BY';

COMMENT ON COLUMN WIDGET.CREATE_TIME IS
'CREATE_TIME';

COMMENT ON COLUMN WIDGET.UPDATE_BY IS
'UPDATE_BY';

COMMENT ON COLUMN WIDGET.UPDATE_TIME IS
'UPDATE_TIME';

