spring:
  #datasource:
  #  url: jdbc:mysql://${redxun.datasource.ip}:3306/oauth-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
  #  username: ${redxun.datasource.username}
  #  password: ${redxun.datasource.password}
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false  #关闭缓存
    prefix: classpath:/templates/
    suffix: .html
    #      mode: LEGACYHTML5
    encoding: UTF-8
      #thymeleaf ends


  cloud:
    nacos:
      discovery:
        metadata:
          developer: ray


redxun:
  oauth2:
    token:
      store:
        type: redis
  swagger:
    enabled: true
    title: 认证中心
    description: 认证中心接口文档
    version: 1.0
    base-package: com.redxun.oauth.controller
  security:
    code:
      # 忽略验证码的应用编号 app
      ignoreClientCode: webApp
