truncate table  sys_tree_cat;
truncate table  sys_tree;
truncate table  sys_dic;
truncate table  sys_route_type;
truncate table  sys_app;
truncate table  sys_menu;
truncate table  sys_transfer_setting;
truncate table  sys_routing;
truncate table  sys_external_api;
